# NupPy

In [1]:
import numpy as np

### ndarray

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [3]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [5]:
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int64')

In [11]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr = np.array([1, 2, 3, 44, 5])

In [21]:
arr.dtype

dtype('int64')

In [23]:
float_arr = arr.astype(np.float64)

In [24]:
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [26]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)